name: ci

on:
  push:
    branches:
      - "*" # matches every branch
      - "*/*" # matches every branch containing a single '/'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.23"

      - name: Setup task
        uses: arduino/setup-task@v1

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run go setup task
        run: task install

      - name: Run go lint task
        run: task lint

      - name: Run go test task
        run: task test
